language: python
python:
- '2.7'
- '3.3'
- pypy


before_install:
- pip install pytest
- pip install coveralls
- pip install pytest-cov
- python setup.py develop

script:
- py.test --cov-report=term --cov=cli tests

after_success:
- coveralls